openapi: "3.0.0"
info:
  version: 1.0.0
  title: Discount Management API
paths:
  /calculate-discount:
    get:
      summary: Calculate discount for requested product count
      operationId: calculateDiscount
      tags:
        - discount
      parameters:
        - name: productID
          in: query
          description: Unique product UUID identifier (ex. 43bcc57b-4538-411f-8f4c-6af4cf046786, feea4b6c-cf3d-4dfc-ae41-49dd9e6b3d5d)
          required: true
          schema:
            type: string
            format: uuid
        - name: productCount
          in: query
          description: Ordered product count
          required: true
          schema:
            type: integer
            format: int64
            maximum: 1000
        - name: discountPolicy
          in: query
          description: Policy to apply discount. You can apply more then one policy.
          required: true
          schema:
            type: array
            minItems: 1
            items:
              $ref: '#/components/schemas/PolicyDTO'
      responses:
        '200':
          description: A discount information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscountDTO"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
  /policy/discounts-levels:
    get:
      summary: Get discount levels for policy
      operationId: getDiscountLevels
      tags:
        - discountPolicy
      parameters:
        - name: policy
          in: query
          description: Policy for discounts
          required: true
          schema:
            $ref: '#/components/schemas/PolicyDTO'
      responses:
        '200':
          description: DiscountsLevel
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DiscountLevelDTO"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
    post:
      summary: Add/Change DiscountLevel
      operationId: changeDiscountLevel
      tags:
        - discountPolicy
      parameters:
        - name: policy
          in: query
          description: Policy for discounts
          required: true
          schema:
            $ref: '#/components/schemas/PolicyDTO'
        - name: discountLevel
          in: query
          description: product count threshold to remove
          required: true
          schema:
            $ref: '#/components/schemas/DiscountLevelDTO'
      responses:
        '201':
          description: DiscountLeve has been add or changed
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
    delete:
      summary: Delete discount level
      operationId: deleteDiscountLevel
      tags:
        - discountPolicy
      parameters:
        - name: policy
          in: query
          description: Policy for DiscountLevel
          required: true
          schema:
            $ref: '#/components/schemas/PolicyDTO'
        - name: productCountThreshold
          in: query
          description: product count threshold to remove
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: DiscountLeve has been removed
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
  /policy:
    get:
      summary: List of polices
      operationId: getPolicies
      tags:
        - discountPolicy
      responses:
        '200':
          description: A available policies list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PolicyDTO"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
components:
  schemas:
    DiscountDTO:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/ProductDTO'
        orderCount:
          type: integer
          maximum: 1000
          format: int64
        discount:
          $ref: '#/components/schemas/PriceDTO'
        policies:
          type: array
          items:
            $ref: '#/components/schemas/PolicyDTO'
    ProductDTO:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          $ref: '#/components/schemas/PriceDTO'
    PolicyDTO:
      type: string
      enum:
        - AMOUNT_BASED
        - PERCENTAGE_BASED
    PriceDTO:
      type: object
      required:
        - price
        - denomination
      properties:
        value:
          type: number
          format: currency
        denomination:
          type: string
          enum:
            - PLN
            - USD
            - EUR
    DiscountLevelDTO:
      type: object
      properties:
        productCountThreshold:
          type: number
          format: int64
        discountValue:
          type: string
          format: json
    ErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string