openapi: "3.0.0"
info:
  version: 1.0.0
  title: Discount Management API
paths:
  /discount:
    get:
      summary: Get discount for requested product count
      operationId: getDiscount
      tags:
        - discount
      parameters:
        - name: productID
          in: query
          description: Unique product UUID identifier (ex. 43bcc57b-4538-411f-8f4c-6af4cf046786, feea4b6c-cf3d-4dfc-ae41-49dd9e6b3d5d)
          required: true
          schema:
            type: string
            format: uuid
        - name: productCount
          in: query
          description: Ordered product count
          required: true
          schema:
            type: integer
            format: int64
            maximum: 1000
        - name: discountPolicy
          in: query
          description: Policy to apply discount. You can apply more then one policy.
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PolicyDTO'
      responses:
        '200':
          description: A discount information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscountDTO"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
  /policies:
    get:
      summary: List of polices
      operationId: getPolicies
      tags:
        - policy
      responses:
        '200':
          description: A available policies list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PolicyDTO"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
components:
  schemas:
    DiscountDTO:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/ProductDTO'
        orderCount:
          type: integer
          maximum: 1000
          format: int64
        discount:
          $ref: '#/components/schemas/PriceDTO'
        policies:
          type: array
          items:
            $ref: '#/components/schemas/PolicyDTO'
    ProductDTO:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          $ref: '#/components/schemas/PriceDTO'
    PolicyDTO:
      type: string
      enum:
        - AMOUNT_BASED
        - PERCENTAGE_BASED
    PriceDTO:
      type: object
      required:
        - value
        - denomination
      properties:
        value:
          type: number
          format: currency
        denomination:
          type: string
          enum: [ "PLN","USD","EUR" ]
    ErrorDTO:
      type: object
      required:
        - code
        - message
        - correlationId
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        correlationId:
          type: string
          format: uuid