spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true
      path: /h2
springdoc:
  show-actuator: true
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs